name: Build SolidworksWrapper

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build SolidworksWrapper
      run: msbuild SolidworksWrapper.sln /p:Configuration=Release
      
    - name: Upload SolidworksWrapper DLL
      uses: actions/upload-artifact@v4
      with:
        name: SolidworksWrapper
        path: SolidworksWrapper/bin/Release/SolidworksWrapper.dll
